# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('name_archivo', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id_aux', models.AutoField(primary_key=True, serialize=False)),
                ('uno_aux', models.CharField(blank=True, max_length=128)),
                ('dos_aux', models.CharField(blank=True, max_length=128)),
                ('tres_aux', models.CharField(blank=True, max_length=128)),
                ('cuatro_aux', models.CharField(blank=True, max_length=128)),
                ('cinco_aux', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=128, unique=True)),
                ('image_categoria', models.ImageField(blank=True, upload_to='img_categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('code_admin_inv', models.CharField(blank=True, max_length=128)),
                ('contract_subtype_inv', models.CharField(blank=True, max_length=100)),
                ('province_inv', models.CharField(blank=True, max_length=128)),
                ('zone_inv', models.CharField(blank=True, max_length=128)),
                ('id_type_inv', models.CharField(blank=True, max_length=128)),
                ('operator_inv', models.CharField(blank=True, max_length=128)),
                ('speed_inv', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_link', models.CharField(default=0, max_length=128, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('image_link', models.ImageField(blank=True, upload_to='img_categorias')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id_men', models.AutoField(primary_key=True, serialize=False)),
                ('date_men', models.DateField(default=django.utils.timezone.now)),
                ('description_men', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SustratosCatalogados',
            fields=[
                ('id_sus_cat', models.AutoField(primary_key=True, serialize=False)),
                ('administrativo', models.CharField(blank=True, max_length=128)),
                ('sustrato_red', models.CharField(blank=True, max_length=128)),
                ('sustrato_operadora', models.CharField(blank=True, max_length=128)),
                ('año', models.CharField(blank=True, max_length=128)),
                ('mes', models.CharField(blank=True, max_length=128)),
                ('semana', models.CharField(blank=True, max_length=128)),
                ('semana_estudio', models.CharField(blank=True, max_length=128)),
                ('imputable', models.CharField(blank=True, max_length=128)),
                ('kpi11b', models.CharField(blank=True, max_length=128)),
                ('contrato', models.CharField(blank=True, max_length=128)),
                ('subtipo_contrato', models.CharField(blank=True, max_length=128)),
                ('id_tipo_contrato', models.CharField(blank=True, max_length=128)),
                ('sla', models.CharField(blank=True, max_length=128)),
                ('fuera_de_sla', models.CharField(blank=True, max_length=128)),
                ('tiempo_fuera_vs_sla_tiempo_reparacion', models.CharField(blank=True, max_length=128)),
                ('fuera_sla_tiempo_reparacion', models.CharField(blank=True, max_length=128)),
                ('zona', models.CharField(blank=True, max_length=128)),
                ('provincia', models.CharField(blank=True, max_length=128)),
                ('territorio', models.CharField(blank=True, max_length=128)),
                ('serie', models.CharField(blank=True, max_length=128)),
                ('tipo_de_servicio', models.CharField(blank=True, max_length=100)),
                ('zona_zac', models.CharField(blank=True, max_length=128)),
                ('comentarios_de_apertura', models.CharField(blank=True, max_length=255)),
                ('fecha_de_apertura', models.CharField(blank=True, max_length=128)),
                ('fecha_de_franqueo', models.CharField(blank=True, max_length=128)),
                ('fecha_de_cierre', models.CharField(blank=True, max_length=128)),
                ('tiempo_efectivo', models.CharField(blank=True, max_length=128)),
                ('tiempo_total', models.CharField(blank=True, max_length=128)),
                ('paradas', models.CharField(blank=True, max_length=128)),
                ('causa_del_problema', models.CharField(blank=True, max_length=255)),
                ('imputado_a', models.CharField(blank=True, max_length=128)),
                ('velocidad', models.CharField(blank=True, max_length=128)),
                ('causa', models.CharField(blank=True, max_length=128)),
                ('sustrato', models.CharField(blank=True, max_length=128)),
                ('owner', models.CharField(blank=True, max_length=128)),
                ('final_imputado_a', models.CharField(blank=True, max_length=128)),
                ('tiempo', models.CharField(blank=True, max_length=128)),
                ('revisar_tiempos', models.CharField(blank=True, max_length=128)),
                ('imputacion_revisada', models.CharField(blank=True, max_length=128)),
                ('fecha_franqueo_revisada', models.CharField(blank=True, max_length=128)),
                ('tiempo_revisado', models.CharField(blank=True, max_length=128)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('comentarios', models.CharField(blank=True, max_length=255)),
                ('primera_semana', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SustratosOriginales',
            fields=[
                ('id_sus_gen', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(blank=True, max_length=128)),
                ('territorio', models.CharField(blank=True, max_length=128)),
                ('serie', models.CharField(blank=True, max_length=128)),
                ('secuencia', models.CharField(blank=True, max_length=128, unique=True)),
                ('administrativo', models.CharField(blank=True, max_length=128)),
                ('tipo_de_servicio', models.CharField(blank=True, max_length=100)),
                ('zona_zac', models.CharField(blank=True, max_length=128)),
                ('comentarios_de_apertura', models.CharField(blank=True, max_length=255)),
                ('fecha_de_apertura', models.CharField(blank=True, max_length=128)),
                ('fecha_de_franqueo', models.CharField(blank=True, max_length=128)),
                ('fecha_de_cierre', models.CharField(blank=True, max_length=128)),
                ('tiempo_efectivo', models.CharField(blank=True, max_length=128)),
                ('tiempo_total', models.CharField(blank=True, max_length=128)),
                ('paradas', models.CharField(blank=True, max_length=128)),
                ('causa_del_problema', models.CharField(blank=True, max_length=255)),
                ('tipo_de_causa', models.CharField(blank=True, max_length=128)),
                ('reiterada', models.CharField(blank=True, max_length=128)),
                ('imputado_a', models.CharField(blank=True, max_length=128)),
                ('nif', models.CharField(blank=True, max_length=128)),
                ('operadora', models.CharField(blank=True, max_length=128)),
                ('velocidad', models.CharField(blank=True, max_length=128)),
                ('reabierta', models.CharField(blank=True, max_length=128)),
                ('raiz', models.CharField(blank=True, max_length=128)),
                ('raiz_maxima', models.CharField(blank=True, max_length=128)),
                ('domicilio_cliente_origen', models.CharField(blank=True, max_length=128)),
                ('domicilio_cliente_destino', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('activado', models.BooleanField(default=False)),
                ('catSugerida', models.ManyToManyField(blank=True, related_name='cat_sugerida', to='app.Categoria')),
                ('categoria', models.ManyToManyField(blank=True, to='app.Categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
