# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id_aux', models.AutoField(primary_key=True, serialize=False)),
                ('uno_aux', models.CharField(blank=True, max_length=45, null=True)),
                ('dos_aux', models.CharField(blank=True, max_length=45, null=True)),
                ('tres_aux', models.CharField(blank=True, max_length=45, null=True)),
                ('cuatro_aux', models.CharField(blank=True, max_length=45, null=True)),
                ('cinco_aux', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=128, unique=True)),
                ('image_categoria', models.ImageField(blank=True, upload_to='img_categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('code_admin_inv', models.IntegerField(unique=True)),
                ('contract_subtype_inv', models.CharField(blank=True, max_length=100, null=True)),
                ('province_inv', models.CharField(blank=True, max_length=45, null=True)),
                ('zone_inv', models.IntegerField(blank=True, null=True)),
                ('id_type_inv', models.CharField(blank=True, max_length=45, null=True)),
                ('operator_inv', models.CharField(blank=True, max_length=45, null=True)),
                ('speed_inv', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_link', models.CharField(default=0, max_length=128, unique=True)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('image_link', models.ImageField(blank=True, upload_to='img_categorias')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id_men', models.AutoField(primary_key=True, serialize=False)),
                ('date_men', models.DateField()),
                ('description_men', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Substrata',
            fields=[
                ('id_sub_sub', models.AutoField(primary_key=True, serialize=False)),
                ('province_sub', models.CharField(max_length=45)),
                ('territory_sub', models.CharField(max_length=45)),
                ('series_sub', models.IntegerField()),
                ('service_type_sub', models.CharField(max_length=100)),
                ('zac_zone_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('opening_remarks_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_date_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('postage_date_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('closing_date_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('effective_time_sub', models.FloatField(blank=True, null=True)),
                ('total_time_sub', models.FloatField(blank=True, null=True)),
                ('stops_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('causes_problems_sub', models.CharField(blank=True, max_length=255, null=True)),
                ('cause_types_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('imputed_sub', models.CharField(blank=True, max_length=45, null=True)),
                ('speed_sub', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubstrataCataloged',
            fields=[
                ('id_sub_cat', models.AutoField(primary_key=True, serialize=False)),
                ('substrata_red_cat', models.CharField(max_length=45)),
                ('substrata_operator_cat', models.CharField(max_length=45)),
                ('year_cat', models.IntegerField()),
                ('month_cat', models.CharField(max_length=45)),
                ('week_cat', models.IntegerField()),
                ('study_week_cat', models.IntegerField()),
                ('impute_cat', models.CharField(max_length=45)),
                ('rpb_cat', models.CharField(max_length=45)),
                ('contract_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('contract_subtype_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('contract_type_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('sla_cat', models.IntegerField(blank=True, null=True)),
                ('slaout_cat', models.IntegerField(blank=True, null=True)),
                ('timeout_vs_sla_repair_cat', models.FloatField(blank=True, null=True)),
                ('slaout_repair_cat', models.IntegerField(blank=True, null=True)),
                ('zone_cat', models.IntegerField(blank=True, null=True)),
                ('fail_type_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('substrata_cat', models.CharField(max_length=45)),
                ('owner_cat', models.CharField(max_length=45)),
                ('imputed_cat', models.CharField(max_length=45)),
                ('timereview_cat', models.IntegerField()),
                ('impute_review_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('postage_date_review_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('time_review_cat', models.CharField(blank=True, max_length=45, null=True)),
                ('description_review_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('comments_review_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('firstweek_review_cat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubstrataGeneral',
            fields=[
                ('id_sub_gen', models.AutoField(primary_key=True, serialize=False)),
                ('secuence_gen', models.CharField(max_length=45, unique=True)),
                ('cause_type_gen', models.CharField(max_length=45)),
                ('reiterated_gen', models.IntegerField()),
                ('nif_gen', models.CharField(max_length=45)),
                ('operator_gen', models.CharField(max_length=45)),
                ('reopen_gen', models.IntegerField()),
                ('root_gen', models.CharField(blank=True, max_length=45, null=True)),
                ('root_max_gen', models.CharField(blank=True, max_length=45, null=True)),
                ('origin_adress_gen', models.CharField(max_length=45)),
                ('final_adress_gen', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('activado', models.BooleanField(default=False)),
                ('catSugerida', models.ManyToManyField(blank=True, related_name='cat_sugerida', to='app.Categoria')),
                ('categoria', models.ManyToManyField(blank=True, to='app.Categoria')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='substratageneral',
            name='id_user_gen',
            field=models.ForeignKey(db_column='id_user_gen', on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='substratacataloged',
            name='id_user_cat',
            field=models.ForeignKey(db_column='id_user_cat', on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='substrata',
            name='fk_sub_cat',
            field=models.ForeignKey(db_column='fk_sub_cat', on_delete=django.db.models.deletion.CASCADE, to='app.SubstrataCataloged'),
        ),
        migrations.AddField(
            model_name='substrata',
            name='fk_sub_gen',
            field=models.ForeignKey(db_column='fk_sub_gen', on_delete=django.db.models.deletion.CASCADE, to='app.SubstrataGeneral'),
        ),
        migrations.AddField(
            model_name='substrata',
            name='id_admin_sub',
            field=models.ForeignKey(db_column='id_admin_sub', on_delete=django.db.models.deletion.CASCADE, to='app.Inventario'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='id_receive_men',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_receive_men', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='id_send_men',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_send_men', to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_user_inv',
            field=models.ForeignKey(db_column='id_user_inv', on_delete=django.db.models.deletion.CASCADE, to='app.Usuario'),
        ),
    ]
